config/routes.rb
Serv::Application.routes.draw do
  get 'users', to:"users#index"
  get 'user', to:"users#show"

  devise_for :users

  resources :dashboard

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, :format => {with: /[A-ZА-Я][a-zа-я]+(\s|,)[A-ZА-Я][a-zа-я]{1,19}/, message: "Формат: Имя Фамилия" }, :uniqueness => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to controller: 'dashboard', action: 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1> you are welkome to dashboard!</h1>

app/views/home/index.html.erb
<h1>You are welkome to home page!</h1>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <nav class='container-fluid'>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse ">
        <a class="brand" href="#">Devise</a>

        <ul class="nav">
          <li><%= link_to "Price List" %></li>
          <li><%= link_to "Contact Us" %></li>
        </ul>

        <div class='nav'>
        <%= form_tag 'companies_path', :method => 'get', class:'navbar-form navbar-left', role:'search' do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], class:'form-control', placeholder:'Найти ...' %>
              <%= submit_tag 'Поиск', :name => nil, class:'btn btn-default' %>
            </div>
        <% end %>
        </div>

        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
              <li><%= link_to current_user.email, user_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Users page', user_path %></li>
                  <li><%= link_to 'All users', users_path %></li>
                  <li><%= link_to 'Settings', edit_user_registration_path%></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serv</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => 'flash_#{name}' %>
  <% end %>

  <div class='container'>
    <div class="col-md-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>
  <p>
    <%= user.username %><br>
    <%= user.email %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>Show</h1>

<%= current_user.username %><br>
<%= current_user.email %>